name: wiifd
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutterfire_ui: ^0.2.0+2
  date_format: ^2.0.4
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.3
  cloud_firestore: ^3.1.4
  google_sign_in: ^5.2.1
  flutter_riverpod: ^1.0.3
  supabase: ^0.2.10
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  logger: ^1.1.0
  uuid: ^3.0.5
  google_sign_in_mocks: ^0.2.1
  firebase_auth_mocks: ^0.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.1
  build_runner: ^2.1.7
  mocktail: ^0.2.0





flutter:

  uses-material-design: true

  assets:
  - assets/images/
  #   - images/a_dot_ham.jpeg

