// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcIbqz68ODudgFYBcDZXoiAqcdjKEfLko',
    appId: '1:928487410803:web:8cfd7a0f956bd82cf82e06',
    messagingSenderId: '928487410803',
    projectId: 'iiiiisssss',
    authDomain: 'iiiiisssss.firebaseapp.com',
    storageBucket: 'iiiiisssss.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArC_eM4uosfPdzrAgopK8nO9E2c7EfSb4',
    appId: '1:928487410803:android:a8f22b2c09588997f82e06',
    messagingSenderId: '928487410803',
    projectId: 'iiiiisssss',
    storageBucket: 'iiiiisssss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiXiZJdihR0TkDsgAQ53sJULdPQrPwSDc',
    appId: '1:928487410803:ios:7c216b2ef54a5271f82e06',
    messagingSenderId: '928487410803',
    projectId: 'iiiiisssss',
    storageBucket: 'iiiiisssss.appspot.com',
    iosClientId: '928487410803-ucb3ctpvlhburgrgssfvvq28b3q84ju6.apps.googleusercontent.com',
    iosBundleId: 'wiif.dwiif.wiifd',
  );
}
