name: CI
on:
 pull_request:
   branches:
   - master

jobs:
  flutter_test:
   name: Run wiifd
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@V1
       with:
         java-vertion: "12.x"
     - uses: subosito/flutter-action@V1
       with:
         channel: "stable"
     - run: flutter pub get
     - run: flutter analyze
     - run: flutter test






